# Generated by Django 3.2.3 on 2021-07-01 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('description', models.TextField(max_length=128, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Franchising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'франшиза',
                'verbose_name_plural': 'Франшиза',
            },
        ),
        migrations.CreateModel(
            name='Menue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=128, verbose_name='Блюдо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=128, verbose_name='Бар')),
                ('start', models.DateTimeField(verbose_name='От')),
                ('end', models.DateTimeField(verbose_name='До')),
                ('persons', models.IntegerField(verbose_name='Кол-во человек')),
                ('table', models.IntegerField(verbose_name='Стол')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон для связи')),
                ('description', models.TextField(max_length=128, verbose_name='Пожелание к брони')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'Бронирование',
            },
        ),
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('schema', models.CharField(max_length=128, verbose_name='Схема зала')),
            ],
            options={
                'verbose_name': 'ресторан',
                'verbose_name_plural': 'рестораны',
            },
        ),
        migrations.CreateModel(
            name='Сareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('bar', models.CharField(max_length=128, verbose_name='Бар')),
                ('b_day', models.DateField(verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=128, verbose_name='Гражданство')),
                ('about', models.TextField(max_length=128, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'карьера',
                'verbose_name_plural': 'Карьеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='restaurant.restaraunt', verbose_name='Ресторан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='MenuInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.menue', verbose_name='Меню')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='menue',
            name='restaraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.restaraunt', verbose_name='Ресторан'),
        ),
    ]
