# Generated by Django 3.2.3 on 2022-01-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menueinrestaraunt',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доступности ДО'),
        ),
        migrations.AddField(
            model_name='menueinrestaraunt',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доступности ОТ'),
        ),
        migrations.AddField(
            model_name='phototable',
            name='description',
            field=models.TextField(default='', max_length=128, verbose_name='Описание стола'),
        ),
        migrations.AlterField(
            model_name='phototable',
            name='restaraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tables', to='restaurant.restaraunt', verbose_name='Ресторан'),
        ),
    ]
