# Generated by Django 3.2.3 on 2021-07-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bar',
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaraunt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='restaurant.restaraunt', verbose_name='Ресторан'),
        ),
    ]
