# Generated by Django 3.2.3 on 2021-08-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210702_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='menue',
            name='description',
            field=models.TextField(default='', max_length=600, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='menue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='menue',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='menue',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
