# Generated by Django 3.2.9 on 2022-01-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0003_auto_20220112_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'В ожидании'), (1, 'Подтвержден'), (2, 'Отклонен')], default=0, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'В ожидании'), (1, 'Подтверждена'), (2, 'Отклонена')], default=0, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='setting',
            name='allow_period_reservation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доступный период бронирования (+ дней)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='allow_time_reservation_end',
            field=models.TimeField(blank=True, help_text='ДО', null=True, verbose_name='Доступное время бронирование'),
        ),
        migrations.AddField(
            model_name='setting',
            name='allow_time_reservation_start',
            field=models.TimeField(blank=True, help_text='С', null=True, verbose_name='Доступное время бронирование'),
        ),
        migrations.AddField(
            model_name='setting',
            name='main_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Главный баннер на странице'),
        ),
    ]
