# Generated by Django 3.2.3 on 2021-08-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210831_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menue',
            name='weight',
            field=models.CharField(default='', max_length=128, verbose_name='Вес'),
        ),
    ]
