# Generated by Django 3.2.9 on 2022-02-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220126_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
