# Generated by Django 3.2.9 on 2022-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_profile_is_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_weekend_time_reservation_end',
            field=models.TimeField(blank=True, help_text='ДО', null=True, verbose_name='Доступное время бронирования(птн-сб)'),
        ),
        migrations.AddField(
            model_name='setting',
            name='allow_weekend_time_reservation_start',
            field=models.TimeField(blank=True, help_text='С', null=True, verbose_name='Доступное время бронирования(птн-сб)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='allow_time_reservation_end',
            field=models.TimeField(blank=True, help_text='ДО', null=True, verbose_name='Доступное время бронирования(вск-чтв)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='allow_time_reservation_start',
            field=models.TimeField(blank=True, help_text='С', null=True, verbose_name='Доступное время бронирования(вск-чтв)'),
        ),
    ]
