# Generated by Django 3.2.3 on 2021-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='schema',
            field=models.ImageField(upload_to='tables/', verbose_name='Схема зала (SVG)'),
        ),
    ]
