# Generated by Django 3.2.3 on 2021-08-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaraunt_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaraunt',
            name='schema',
        ),
        migrations.CreateModel(
            name='RestarauntSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.ImageField(upload_to='tables/', verbose_name='Схема зала (SVG)')),
                ('description', models.TextField(default='', max_length=150, verbose_name='Описание')),
                ('restaraunt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaraunt')),
            ],
            options={
                'verbose_name': 'ресторан',
                'verbose_name_plural': 'рестораны',
            },
        ),
    ]
