# Generated by Django 3.2.9 on 2022-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20220304_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_time_delivery_end',
            field=models.TimeField(blank=True, help_text='ДО', null=True, verbose_name='Доступное время доставки'),
        ),
        migrations.AddField(
            model_name='setting',
            name='allow_time_delivery_start',
            field=models.TimeField(blank=True, help_text='С', null=True, verbose_name='Доступное время доставки'),
        ),
    ]
