# Generated by Django 3.2.3 on 2021-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210831_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restarauntschema',
            name='schema',
            field=models.FileField(upload_to='tables/', verbose_name='Схема зала (SVG)'),
        ),
    ]
