# Generated by Django 3.2.3 on 2021-09-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restarauntschema_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='menue',
            name='ident',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ident RKeeper'),
        ),
        migrations.AlterField(
            model_name='restarauntschema',
            name='restaraunt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schemes', to='restaurant.restaraunt'),
        ),
    ]
