# Generated by Django 3.2.3 on 2021-09-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20210901_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Родитель'),
        ),
    ]
