# Generated by Django 3.2.3 on 2021-09-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=128, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('link', models.TextField(max_length=128, verbose_name='Ссылка')),
            ],
        ),
    ]
