# Generated by Django 3.2.9 on 2022-03-31 16:33

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_setting_main_banner_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', null=True, verbose_name='Временная зона'),
        ),
    ]
