# Generated by Django 3.2.3 on 2021-09-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'событие', 'verbose_name_plural': 'Событие'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
    ]
