# Generated by Django 3.2.9 on 2022-03-31 21:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_city_city_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menue',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
