# Generated by Django 3.2.3 on 2021-09-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20210906_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Онлайн оплата'), (1, 'Картой')], default=0, verbose_name='Тип оплаты'),
        ),
    ]
