# Generated by Django 3.2.9 on 2022-04-01 09:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_menue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='payment_and_return',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Оплата и возврат'),
        ),
    ]
