# Generated by Django 3.2.9 on 2022-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20220407_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='career_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='почта для отправки анкет по карьере'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='feedback_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='почта для отправки отзывов'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='franchising_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='почта для заявок на франшизу'),
        ),
    ]
