# Generated by Django 3.2.3 on 2021-09-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='restaraunt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaraunt', verbose_name='Ресторан'),
        ),
    ]
