# Generated by Django 3.2.9 on 2022-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20220408_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='menue',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активен?'),
        ),
    ]
