# Generated by Django 3.2.9 on 2022-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_menue_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='filepdf',
            field=models.FileField(blank=True, null=True, upload_to='preorders/', verbose_name='Файл предзаказа'),
        ),
    ]
