# Generated by Django 3.2.3 on 2021-11-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20210928_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='company',
            field=models.CharField(blank=True, max_length=228, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='r_keeper',
            field=models.CharField(blank=True, max_length=228, null=True, verbose_name='RKeeper'),
        ),
    ]
