# Generated by Django 3.2.9 on 2022-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20220429_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='payment_key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ терминала для оплаты'),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='payment_terminal_id',
            field=models.CharField(default='', max_length=255, verbose_name='ИД терминала для оплаты'),
        ),
    ]
