# Generated by Django 3.2.3 on 2021-11-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20211101_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='payment_token',
            field=models.CharField(blank=True, max_length=228, null=True, verbose_name='Token for Payment'),
        ),
    ]
