# Generated by Django 3.2.3 on 2021-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_restaraunt_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='payment_terminal_id',
            field=models.CharField(blank=True, max_length=228, null=True, verbose_name='Terminal id for Payment'),
        ),
    ]
