# Generated by Django 3.2.3 on 2021-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_restaraunt_payment_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menue',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный'),
        ),
    ]
