# Generated by Django 3.2.3 on 2021-06-21 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=128, verbose_name='Блюдо')),
                ('category', models.CharField(max_length=128, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('schema', models.CharField(max_length=128, verbose_name='Схема зала')),
            ],
            options={
                'verbose_name': 'ресторан',
                'verbose_name_plural': 'рестораны',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('second_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('registration_ip', models.GenericIPAddressField(default='192.168.0.1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('menue', models.ManyToManyField(related_name='menue', to='restaurant.Menue')),
                ('restaraunt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='restaurant.restaraunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='menue',
            name='restaraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.restaraunt'),
        ),
    ]
