# Generated by Django 3.2.3 on 2021-06-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
