# Generated by Django 3.2.3 on 2021-06-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категория')),
            ],
        ),
        migrations.AlterField(
            model_name='menue',
            name='restaraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.restaraunt', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='restaurant.restaraunt', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='menue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.category', verbose_name='Категория'),
        ),
    ]
