# Generated by Django 3.2.3 on 2021-06-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210621_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='menue',
        ),
        migrations.CreateModel(
            name='MenuInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.menue', verbose_name='Меню')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menues', to='restaurant.order', verbose_name='Заказ')),
            ],
        ),
    ]
